shell.executable("bash")

rule all:
    input:
        "test.vcf.gz"

rule A:
    input:
        "test1.vcf"
    output:
        "test1.vcf.gz"
    wrapper:
        "0.42.0/bio/vcf/compress"

use rule A as B with:
    output:
        "test.vcf.gz"
    wrapper:
        "0.42.0/bio/vcf/compress"